## Lab: Installing the OpenShift CLI

### Command Line Interface

OpenShift ships with a feature rich web console as well as command line tools to provide users with a nice interface to work with applications deployed to the platform. The OpenShift tools are a single executable written in the Go programming language and is available for the following operating systems:

- Microsoft Windows
- Apple OS X
- Linux

#### Downloading the tools
During this lab, we are going to download the client tool and add them to our operating system $PATH environment variables so the executable is accessible from any directory on the command line.

The first thing we want to do is download the correct executable for your operating system as linked below:

- {{DOWNLOAD_CLIENT_WINDOWS}}[Microsoft Windows]
- {{DOWNLOAD_CLIENT_MAC}}[Apple OS X]
- {{DOWNLOAD_CLIENT_LIN64}}[Linux 64]
{% if DOWNLOAD_CLIENT_LIN32.empty? %}
- {{DOWNLOAD_CLIENT_LIN32}}[Linux 32]
{% endif %}

Once the file has been downloaded, we would suggest saving this file to the following directories:

**Windows:**

[source]
----
C:\OpenShift
----

**OS X:**

[source]
----
~/OpenShift
----

**Linux:**

[source]
----
~/OpenShift
----


#### Adding `oc` to your PATH

**Windows:**

Because changing your PATH on windows varies by version of the operating system, we will not list each operating system here. However, the general workflow is right click on your computer name inside of the file explorer. Select Advanced system settings. Click on the advanced tab, and then finally click on Environment variables. Once the new dialog opens, select the Path variable and add ";C:\OpenShift" at the end. For an easy way out, you could always just copy it to C:\Windows or a directory you know is already on your path. For more detailed instructions:

https://support.microsoft.com/en-us/kb/310519[Windows XP]

http://banagale.com/changing-your-system-path-in-windows-vista.htm[Windows Vista]

http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx[Windows 7]

http://www.itechtics.com/customize-windows-environment-variables/[Windows 8]

Windows 10 - Follow the directions above.

**OS X:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

**Linux:**

[source]
----
$ export PATH=$PATH:~/OpenShift
----

#### Verify
At this point, we should have the oc tool available for use. Let's test this out by printing the version of the `oc` command:

[source]
----
$ oc version
----

You should see the following (or something similar):

[source]
----
{{OC_VERSION}}
----

If you get an error message, you have not updated your path correctly.
