---
id: training
name: APPUiO Tech Labs

content:
  url: https://raw.githubusercontent.com/appuio/workshopper-content/master

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  PARKSMAP_IMAGENAME: "parksmap"
  PARKSMAP_VERSION: "1.2.0"
  PARKSMAP_PY: true
  NATIONALPARKS_VERSION: "1.2.1"
  MLBPARKS_VERSION: "1.0.0"
  DOWNLOAD_CLIENT_WINDOWS: https://ose3-lab-master.puzzle.ch:8443/console/extensions/clients/windows/oc.exe
  DOWNLOAD_CLIENT_MAC: https://ose3-lab-master.puzzle.ch:8443/console/extensions/clients/macosx/oc
  DOWNLOAD_CLIENT_LIN64: https://ose3-lab-master.puzzle.ch:8443/console/extensions/clients/linux/oc
  OC_VERSION: "oc v3.4.1.44\nkubernetes v1.4.0+776c994"
  GIT_HOST: github
  DOCS_URL: docs.openshift.org

modules:
  activate:
  - install
  - explore
  - parksmap-architecture
  - docker
  - scaling
  - routes
  - permissions
  - python
  - databases-py
  - application-health
  - codechanges
  - templates
